spring:
  application:
    name: user-center-backend
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 62824658
      url: jdbc:mysql://localhost:3306/mybatis-plus-demo


server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

